# @format

version: "version"
services:
  nginx-front:
    image: nginx:1.25.4
    volumes:
      - ./frontend:/code
      - ./docker/nginx-front.conf:/etc/nginx/conf.d/nginx-front.conf
    networks:
      net:
        ipv4_address: 192.168.240.2
  nginx-back:
    image: nginx:1.25.4
    volumes:
      - ./backend:/code
      - ./docker/nginx-back.conf:/etc/nginx/conf.d/nginx-back.conf
    networks:
      net:
        ipv4_address: 192.168.240.3
  python-back:
    image: python:3.9.18
    volumes:
      - ./backend:/code
    networks:
      net:
        ipv4_address: 192.168.240.4
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24


